#!/usr/bin/env python3
"""Merge channel descriptions generated by the research notebooks.

The notebooks under ``research/Jules``, ``research/codex``, and
``research/copilot`` each cache their own Gemini-generated channel descriptions in
Google Drive.  This utility reads those Drive artifacts and writes a single
channel-indexed object where every channel contains one description from each
subdirectory source.

The description text is prefixed with the subdirectory name, e.g.
``"copilot: ..."``, so downstream consumers can compare descriptions without
losing provenance.
"""

from __future__ import annotations

import argparse
import glob
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

DRIVE_ROOT = Path("/content/drive/MyDrive")

DEFAULT_SOURCES = {
    "Jules": DRIVE_ROOT / "research/channel_descriptions_and_segments.json",
    "codex": DRIVE_ROOT / "Graphiko/research/semantic_description_pointcloud_alignment/descriptions/by_channel",
    "copilot": DRIVE_ROOT / "Research/channel_descriptions/latest/all_channels.json",
}

DEFAULT_OUTPUT = (
    DRIVE_ROOT
    / "Graphiko/research/merged_channel_descriptions/latest/all_channel_descriptions_by_source.json"
)


def _read_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def _as_text(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value.strip()
    # Preserve structured fields when a notebook stored a richer object than a
    # plain text description.
    return json.dumps(value, ensure_ascii=False, sort_keys=True).strip()


def _extract_description(payload: dict[str, Any]) -> str:
    """Return the most complete text description from a channel artifact."""
    parts: list[str] = []

    # Jules and copilot use `description`; codex uses short/detailed fields.
    for key in ("description", "short_description", "detailed_description"):
        text = _as_text(payload.get(key))
        if text:
            parts.append(text)

    if parts:
        return "\n\n".join(dict.fromkeys(parts))

    # Last-resort fallback: keep a compact representation instead of silently
    # dropping an otherwise valid channel artifact.
    return _as_text(payload)


def _load_channel_mapping(path: Path) -> dict[str, dict[str, Any]]:
    """Load a channel -> artifact mapping from a JSON file or JSON directory."""
    if path.is_dir():
        channels: dict[str, dict[str, Any]] = {}
        for filename in sorted(glob.glob(str(path / "*.json"))):
            payload = _read_json(Path(filename))
            if not isinstance(payload, dict):
                continue
            channel = payload.get("channel_name") or payload.get("channel") or Path(filename).stem
            channels[str(channel)] = payload
        return channels

    payload = _read_json(path)
    if not isinstance(payload, dict):
        raise ValueError(f"Expected JSON object at {path}, got {type(payload).__name__}")

    # copilot's combined artifact shape: { ..., "channels": {channel: artifact}}
    if isinstance(payload.get("channels"), dict):
        return {
            str(channel): artifact if isinstance(artifact, dict) else {"description": artifact}
            for channel, artifact in payload["channels"].items()
        }

    # Jules' artifact shape: {channel: {description, segments}}
    return {
        str(channel): artifact if isinstance(artifact, dict) else {"description": artifact}
        for channel, artifact in payload.items()
    }


def merge_descriptions(
    sources: dict[str, Path],
    *,
    require_all_sources: bool = True,
    now: Callable[[], datetime] | None = None,
) -> dict[str, Any]:
    """Build the merged description object.

    Args:
        sources: Mapping from research subdirectory name to its Drive artifact.
        require_all_sources: When true, include only channels that have a
            description in every source so each channel has exactly three
            descriptions.  When false, include the union of channels.
        now: Optional clock injection for deterministic tests.
    """
    loaded = {source: _load_channel_mapping(path) for source, path in sources.items()}
    source_sets = {source: set(channels) for source, channels in loaded.items()}

    if require_all_sources:
        selected_channels = set.intersection(*source_sets.values()) if source_sets else set()
    else:
        selected_channels = set.union(*source_sets.values()) if source_sets else set()

    merged_channels: dict[str, dict[str, str]] = {}
    for channel in sorted(selected_channels):
        per_source: dict[str, str] = {}
        for source in sorted(sources):
            artifact = loaded[source].get(channel)
            if artifact is None:
                continue
            description = _extract_description(artifact)
            if description:
                per_source[source] = f"{source}: {description}"
        if (not require_all_sources) or len(per_source) == len(sources):
            merged_channels[channel] = per_source

    timestamp = (now or (lambda: datetime.now(timezone.utc)))().isoformat()
    return {
        "schema_name": "graphiko.research.merged_channel_descriptions_by_source",
        "schema_version": "1.0.0",
        "generated_at": timestamp,
        "description": (
            "Channel-indexed descriptions merged from the Jules, codex, and "
            "copilot research notebook Drive artifacts. Each description value "
            "is prefixed by its source subdirectory name."
        ),
        "require_all_sources": require_all_sources,
        "sources": {source: str(path) for source, path in sources.items()},
        "source_channel_counts": {
            source: len(channels) for source, channels in loaded.items()
        },
        "channel_count": len(merged_channels),
        "omitted_channels_by_source": {
            source: sorted(set.union(*source_sets.values()) - channels)
            if source_sets
            else []
            for source, channels in source_sets.items()
        },
        "channels": merged_channels,
    }


def _parse_source_overrides(values: list[str]) -> dict[str, Path]:
    sources = dict(DEFAULT_SOURCES)
    for value in values:
        if "=" not in value:
            raise argparse.ArgumentTypeError(
                f"Invalid --source {value!r}; expected NAME=/path/to/artifact"
            )
        name, raw_path = value.split("=", 1)
        sources[name] = Path(raw_path)
    return sources


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        action="append",
        default=[],
        metavar="NAME=PATH",
        help="Override or add a source artifact path. May be repeated.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Merged JSON output path (default: {DEFAULT_OUTPUT}).",
    )
    parser.add_argument(
        "--include-partial-channels",
        action="store_true",
        help="Include channels that are missing one or more source descriptions.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the merged object to stdout instead of writing it.",
    )
    args = parser.parse_args(argv)

    sources = _parse_source_overrides(args.source)
    missing = [str(path) for path in sources.values() if not path.exists()]
    if missing:
        print("Missing source artifact(s):", file=sys.stderr)
        for path in missing:
            print(f"  - {path}", file=sys.stderr)
        return 1

    merged = merge_descriptions(
        sources,
        require_all_sources=not args.include_partial_channels,
    )

    if args.dry_run:
        print(json.dumps(merged, ensure_ascii=False, indent=2))
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as fh:
        json.dump(merged, fh, ensure_ascii=False, indent=2)
        fh.write("\n")

    print(f"Wrote {merged['channel_count']} merged channel descriptions to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
